/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilateur.node;

import compilateur.analysis.*;

@SuppressWarnings("nls")
public final class TCommentaireMultiligne extends Token
{
    public TCommentaireMultiligne(String text)
    {
        setText(text);
    }

    public TCommentaireMultiligne(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCommentaireMultiligne(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCommentaireMultiligne(this);
    }
}
